version: "3.8"
services:
  db:
    build: ./database/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5432" ]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    build: ./app/
    restart:
      on-failure
    depends_on:
      - db